server:
  port: 8000

spring:
  application:
    name: api-gateway
#  data:
#    redis:
#      host: localhost
#      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: public-user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/auth/signup, /api/v1/auth/login, /api/v1/auth/token/validation, /api/v1/auth/refresh-token
              filters: []
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: JwtAuthenticationFilter
logging:
  level:
    org.springframework.cloud.gateway: DEBUG